# -*- coding: utf-8 -*-
"""TRABAJO PRACTICO_Taller_Clase_02_Movilidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aP4U4NME7YVRvp4KR73tYJwxgOUEX-oU

# Taller de movilidad urbana: taxis y clima en Nueva York

**Caso de estudio:** viajes de NYC TLC Yellow Taxi durante enero de 2024.

En este taller construiremos un flujo reproducible: adquisición, inspección, auditoría de calidad, enriquecimiento por zonas, agregación temporal, integración con clima y análisis exploratorio. No buscamos demostrar causalidad, sino aprender a formular y comprobar preguntas con datos reales.

## Objetivos

Al finalizar podrás:

- construir y validar una URL de datos abiertos;
- inspeccionar estructura, tipos y faltantes antes de analizar;
- convertir reglas de calidad en una tabla de auditoría;
- enriquecer viajes mediante uniones `many_to_one`;
- agregar pickups por zona y hora sin sesgar la serie temporal;
- convertir observaciones meteorológicas de UTC a `America/New_York`;
- comunicar patrones y límites de un análisis exploratorio.

> **Pregunta guía:** ¿cómo varían los pickups de Yellow Taxi por lugar y hora, y qué relación exploratoria muestran con temperatura y precipitación?

## Ficha de fuentes

| Fuente | Recurso usado | Papel en el taller |
|---|---|---|
| [NYC TLC Trip Record Data](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page) | Yellow Taxi, enero de 2024 (`yellow_tripdata_2024-01.parquet`) | fecha/hora, zonas, distancia, pasajeros e importes de viajes reportados |
| NYC TLC | [Taxi Zone Lookup](https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv) | traduce `LocationID` a borough, zona y `service_zone` |
| NYC TLC | [Taxi Zone Shapefile](https://d37ci6vzurychx.cloudfront.net/misc/taxi_zones.zip) | geometrías para la extensión espacial opcional |
| [NOAA GHCNh](https://www.ncei.noaa.gov/products/global-historical-climatology-network-hourly) | estación `USW00094728`, año 2024 | observaciones de clima con marcas temporales UTC |

**Periodo común:** enero de 2024 en hora local de Nueva York. Los archivos se leen desde sus URL o desde un directorio temporal; este notebook no guarda datasets en el repositorio. Consulta la documentación y licencias de cada proveedor antes de reutilizar los datos.

## 1. Preparación y modo de ejecución

En Colab normalmente basta con ejecutar los imports. Si falta el motor Parquet, descomenta la instalación. La extensión espacial se instala solo si se desea ejecutar esa sección.
"""

# Instalación opcional para Google Colab/Jupyter (descomentar si hace falta):
# %pip install -q pyarrow
# %pip install -q geopandas folium requests

from io import StringIO
import tempfile
from pathlib import Path
from urllib.request import urlopen

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option("display.max_columns", 50)
plt.style.use("seaborn-v0_8-whitegrid")

# True: primera semana de enero; False: todo enero. No hay muestreo aleatorio.
MODO_CLASE = False
INICIO_MES = pd.Timestamp("2024-01-01")
FIN_MES = pd.Timestamp("2024-02-01")
FIN_ANALISIS = pd.Timestamp("2024-01-08") if MODO_CLASE else FIN_MES
ZONA_HORARIA = "America/New_York"

print(f"Ventana: {INICIO_MES} hasta {FIN_ANALISIS} (fin no incluido)")

"""`MODO_CLASE` limita la lectura mediante un filtro temporal de Parquet cuando el motor lo permite. La selección es una semana completa y determinista, no una muestra aleatoria: así preservamos horas consecutivas y el flujo de agregación. En modo completo, la misma lógica procesa todo enero.

## 2. URL validada y carga reproducible
"""

def construir_url_tlc(tipo, anio, mes):
    """Construye una URL TLC válida para un tipo, año y mes."""
    prefijos = {
        "yellow": "yellow_tripdata",
        "green": "green_tripdata",
        "fhv": "fhv_tripdata",
        "fhvhv": "fhvhv_tripdata",
    }
    if tipo not in prefijos:
        opciones = ", ".join(prefijos)
        raise ValueError(f"tipo debe ser uno de: {opciones}")
    if isinstance(anio, bool) or not isinstance(anio, (int, np.integer)) or not 2009 <= anio <= 2100:
        raise ValueError("anio debe ser un entero entre 2009 y 2100")
    if isinstance(mes, bool) or not isinstance(mes, (int, np.integer)) or not 1 <= mes <= 12:
        raise ValueError("mes debe ser un entero entre 1 y 12")
    archivo = f"{prefijos[tipo]}_{anio}-{mes:02d}.parquet"
    return f"https://d37ci6vzurychx.cloudfront.net/trip-data/{archivo}"

URL_VIAJES = construir_url_tlc("yellow", 2024, 1)
URL_ZONAS = "https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv"
URL_GEOMETRIAS = "https://d37ci6vzurychx.cloudfront.net/misc/taxi_zones.zip"
URL_CLIMA = (
    "https://www.ncei.noaa.gov/oa/global-historical-climatology-network/"
    "hourly/access/by-year/2024/psv/GHCNh_USW00094728_2024.psv"
)
print(URL_VIAJES)

COLUMNAS_VIAJES = [
    "tpep_pickup_datetime", "tpep_dropoff_datetime",
    "passenger_count", "trip_distance", "PULocationID",
    "DOLocationID", "fare_amount", "total_amount",
]
filtros = [
    ("tpep_pickup_datetime", ">=", INICIO_MES.to_pydatetime()),
    ("tpep_pickup_datetime", "<", FIN_ANALISIS.to_pydatetime()),
]

# PyArrow aplica el filtro por fecha al leer los grupos de filas compatibles.
viajes_originales = pd.read_parquet(
    URL_VIAJES, columns=COLUMNAS_VIAJES, filters=filtros, engine="pyarrow"
)
print(f"Viajes cargados: {len(viajes_originales):,}")

"""### Pregunta breve

¿Por qué una semana consecutiva es preferible a una muestra aleatoria si queremos comparar horas y días? Escribe una hipótesis antes de continuar.

<details><summary>Ver respuesta orientativa</summary>Una muestra aleatoria puede dejar horas incompletas y alterar sus conteos. Una ventana consecutiva conserva el orden, los ciclos diarios y el denominador temporal, aunque no necesariamente representa el mes completo.</details>

## 3. Inspección antes de limpiar

No debemos decidir reglas sin conocer el esquema. Observa dimensiones, ejemplos, tipos y faltantes.
"""

print("Shape:", viajes_originales.shape)
display(viajes_originales.head())
print("\nInfo:")
viajes_originales.info()
print("\nTipos:")
display(viajes_originales.dtypes.rename("dtype").to_frame())

faltantes = (
    viajes_originales.isna().sum().rename("n_faltantes").to_frame()
    .assign(porcentaje=lambda x: 100 * x["n_faltantes"] / len(viajes_originales))
    .sort_values("porcentaje", ascending=False)
)
display(faltantes)

"""**Observa:** `passenger_count` puede faltar por la forma de reporte. Su ausencia se conserva y no invalida automáticamente un viaje. Solo marcaremos como problemáticos los valores presentes fuera de un intervalo operativo razonable.

## 4. Calidad y auditoría

Las reglas siguientes son criterios analíticos, no verdades universales. Distancia máxima de 100 millas, hasta 8 pasajeros e importes menores a USD 1,000 son umbrales conservadores para detectar registros extremos o inválidos. Cada regla queda en una columna booleana.
"""

calidad = viajes_originales.copy()
calidad["duracion_min"] = (
    calidad["tpep_dropoff_datetime"] - calidad["tpep_pickup_datetime"]
).dt.total_seconds() / 60

calidad["ok_pickup"] = calidad["tpep_pickup_datetime"].notna() & calidad["tpep_pickup_datetime"].between(INICIO_MES, FIN_ANALISIS, inclusive="left")
calidad["ok_dropoff"] = calidad["tpep_dropoff_datetime"].notna()
calidad["ok_duracion"] = calidad["duracion_min"].gt(0) & calidad["duracion_min"].le(24 * 60)
calidad["ok_distancia"] = calidad["trip_distance"].between(0, 100, inclusive="both")
calidad["ok_id_pickup_presente"] = calidad["PULocationID"].notna()
calidad["ok_id_dropoff_presente"] = calidad["DOLocationID"].notna()
calidad["ok_importes"] = (
    calidad["fare_amount"].between(0, 1_000, inclusive="both")
    & calidad["total_amount"].between(0, 1_000, inclusive="both")
    & calidad["total_amount"].ge(calidad["fare_amount"])
)
calidad["ok_pasajeros"] = calidad["passenger_count"].isna() | calidad["passenger_count"].between(0, 8, inclusive="both")

REGLAS = [c for c in calidad.columns if c.startswith("ok_")]
calidad["registro_valido"] = calidad[REGLAS].all(axis=1)
auditoria = pd.DataFrame({
    "regla": REGLAS,
    "cumplen": [int(calidad[c].sum()) for c in REGLAS],
    "incumplen": [int((~calidad[c]).sum()) for c in REGLAS],
})
auditoria["porcentaje_incumple"] = 100 * auditoria["incumplen"] / len(calidad)
display(auditoria.sort_values("porcentaje_incumple", ascending=False))

# Se mantienen por separado para no borrar silenciosamente información.
viajes_rechazados = calidad.loc[~calidad["registro_valido"]].copy()
viajes_validos = calidad.loc[calidad["registro_valido"]].copy()
print(f"Válidos: {len(viajes_validos):,} | Rechazados: {len(viajes_rechazados):,}")
display(viajes_rechazados[COLUMNAS_VIAJES + ["duracion_min"] + REGLAS].head())

"""### Ejercicio 1: sensibilidad de una regla

Calcula cuántos viajes quedarían fuera si la distancia máxima fuese 50 millas, sin modificar `viajes_validos`.
"""

# Tu respuesta:
# fuera_con_umbral_50 = ...

"""<details><summary>Ver solución</summary>

```python
fuera_con_umbral_50 = (~calidad["trip_distance"].between(0, 50)).sum()
print(fuera_con_umbral_50)
```

Conviene comparar este resultado con `ok_distancia` y justificar el umbral con conocimiento del dominio.
</details>

## 5. Enriquecimiento con zonas

### Objetivo

La tabla de viajes identifica el origen mediante `PULocationID` y el destino mediante `DOLocationID`. Estos códigos son útiles para relacionar tablas, pero no permiten interpretar directamente dónde comenzó o terminó un viaje.

En esta sección agregaremos a cada viaje el nombre de la zona, el borough y la clasificación de servicio tanto del origen como del destino. Conceptualmente:

```text
PULocationID = 161
        ↓
pickup_zone = Midtown Center
pickup_borough = Manhattan
pickup_service_zone = Yellow Zone
```

El enriquecimiento no cambia la unidad de observación: cada fila continúa representando un viaje Yellow Taxi reportado. Solo agrega contexto geográfico a sus identificadores.

### 5.1. El catálogo de zonas

`taxi_zone_lookup.csv` es un **catálogo de correspondencias** publicado por NYC TLC. No contiene viajes: contiene una descripción por `LocationID`.

| Columna | Significado |
|---|---|
| `LocationID` | Identificador numérico de la zona TLC |
| `Borough` | Distrito amplio, como Manhattan, Queens o Brooklyn |
| `Zone` | Nombre específico de la zona TLC |
| `service_zone` | Clasificación operativa, como `Yellow Zone`, `Boro Zone` o `Airports` |

Para que el catálogo pueda representar el lado **uno** de una unión, `LocationID` debe ser único.
"""

zonas = pd.read_csv(URL_ZONAS)
display(zonas.head())
print("Cantidad de zonas:", len(zonas))
print("LocationID es único:", zonas["LocationID"].is_unique)

if zonas["LocationID"].duplicated().any():
    raise ValueError("Taxi Zone Lookup contiene LocationID duplicados")

"""### 5.2. Un catálogo, dos roles

Cada viaje consulta el mismo catálogo desde dos papeles diferentes:

```text
PULocationID → zona de origen o pickup
DOLocationID → zona de destino o dropoff
```

Por eso creamos `zonas_pickup` y `zonas_dropoff`. No son dos catálogos distintos ni duplican los viajes: son dos versiones del mismo catálogo con nombres que explicitan el rol de sus columnas.

| Origen | Destino |
|---|---|
| `pickup_zone` | `dropoff_zone` |
| `pickup_borough` | `dropoff_borough` |
| `pickup_service_zone` | `dropoff_service_zone` |

Renombrar antes de unir evita nombres ambiguos como `Zone_x` y `Zone_y`. `DataFrame.rename()` devuelve estas versiones adaptadas sin modificar `zonas`.
"""

zonas_pickup = zonas.rename(columns={
    "LocationID": "PULocationID", "Borough": "pickup_borough",
    "Zone": "pickup_zone", "service_zone": "pickup_service_zone",
})
zonas_dropoff = zonas.rename(columns={
    "LocationID": "DOLocationID", "Borough": "dropoff_borough",
    "Zone": "dropoff_zone", "service_zone": "dropoff_service_zone",
})

display(zonas_pickup.head(2))
display(zonas_dropoff.head(2))

"""### 5.3. Cardinalidad `many_to_one`

La relación esperada es **muchos viajes → una descripción de zona**. Un mismo `PULocationID` o `DOLocationID` puede aparecer en miles de viajes, pero cada identificador debe aparecer como máximo una vez en el catálogo correspondiente.

`validate="many_to_one"` hace que pandas compruebe esta condición durante la unión. Si el catálogo tuviera dos filas para `LocationID = 161`, tres viajes con ese identificador producirían seis filas:

```text
3 viajes × 2 coincidencias en el catálogo = 6 filas
```

Esa multiplicación inflaría conteos, importes, promedios y mapas. La validación detiene el proceso con un error en lugar de producir silenciosamente un resultado incorrecto. También ayuda a detectar catálogos repetidos, mezcla de versiones o descripciones contradictorias para un mismo ID.

### 5.4. Dos uniones izquierdas

Primero agregamos los atributos del origen y después los del destino. `how="left"` conserva todos los viajes válidos. Si un ID no aparece en el catálogo, el viaje permanece y sus atributos geográficos quedan como `NaN`, lo que permite auditar la falta de correspondencia en vez de eliminarla silenciosamente.
"""

viajes_zonas = (
    viajes_validos.merge(zonas_pickup, on="PULocationID", how="left", validate="many_to_one")
    .merge(zonas_dropoff, on="DOLocationID", how="left", validate="many_to_one")
)

"""### 5.5. Controles posteriores e interpretación

Después de unir comprobamos dos propiedades diferentes:

1. **Conservación de filas:** la cantidad de viajes no debe cambiar.
2. **Cobertura del catálogo:** contamos los viajes cuyo ID no encontró nombre de zona.

`many_to_one` no garantiza cobertura completa ni detecta viajes duplicados, IDs faltantes, nombres incorrectos en una fila única o el uso de la clave equivocada. Por eso se complementa con estos controles y con la revisión semántica de las columnas obtenidas.
"""

assert len(viajes_zonas) == len(viajes_validos), "La unión cambió el número de viajes"

sin_nombre_pickup = viajes_zonas["pickup_zone"].isna().sum()
sin_nombre_dropoff = viajes_zonas["dropoff_zone"].isna().sum()
print("Viajes antes y después:", len(viajes_validos), len(viajes_zonas))
print("Sin zona pickup:", sin_nombre_pickup, "| Sin zona dropoff:", sin_nombre_dropoff)

COLUMNAS_ZONA = [
    "PULocationID", "pickup_borough", "pickup_zone", "pickup_service_zone",
    "DOLocationID", "dropoff_borough", "dropoff_zone", "dropoff_service_zone",
]
display(viajes_zonas[COLUMNAS_ZONA].head())

"""### Resultado de la sección

Cada fila sigue representando un viaje, pero ahora permite interpretar tanto su origen como su destino. Las zonas son áreas geográficas agregadas definidas por TLC: no indican una dirección ni una coordenada exacta, y el enriquecimiento no agrega demanda total, solicitudes no atendidas ni vehículos disponibles.

### Pregunta breve

¿Qué ocurriría si `LocationID = 161` apareciera dos veces en el catálogo y no utilizáramos `validate="many_to_one"`?

<details><summary>Ver respuesta orientativa</summary>Cada viaje con ese identificador encontraría dos coincidencias y aparecería dos veces en el resultado. Los conteos y agregaciones posteriores quedarían inflados. Con `validate="many_to_one"`, pandas detecta que el lado del catálogo no es único y detiene la unión.</details>

## 6. Agregación zona-hora de pickups

Los timestamps TLC se interpretan como hora local. En enero de 2024 no hay transición de horario de verano, pero explicitar la zona horaria evita una unión ambigua con NOAA.
"""

viajes_zonas["pickup_hora"] = (
    viajes_zonas["tpep_pickup_datetime"]
    .dt.tz_localize(ZONA_HORARIA, ambiguous="raise", nonexistent="raise")
    .dt.floor("h")
)
pickups_zona_hora = (
    viajes_zonas.groupby(
        ["pickup_hora", "PULocationID", "pickup_borough", "pickup_zone"],
        observed=True, dropna=False,
    )
    .size().rename("pickups").reset_index()
)
assert pickups_zona_hora.duplicated(["pickup_hora", "PULocationID"]).sum() == 0
display(pickups_zona_hora.head())

"""## 7. Clima: UTC, hora local y resumen horario

GHCNh puede contener varias observaciones dentro de una hora. Seleccionaremos variables numéricas, convertiremos valores no numéricos a faltantes y resumiremos a una fila por hora. Temperatura usa media; precipitación usa suma con `min_count=1` para no convertir una hora totalmente faltante en cero.
"""

COLUMNAS_CLIMA = [
    "STATION", "Station_name", "DATE", "temperature",
    "relative_humidity", "wind_speed", "precipitation", "visibility",
]
with urlopen(URL_CLIMA) as respuesta:
    texto_clima = respuesta.read().decode("utf-8")
clima_bruto = pd.read_csv(StringIO(texto_clima), sep="|", usecols=COLUMNAS_CLIMA, low_memory=False)
assert clima_bruto["STATION"].astype(str).eq("USW00094728").all()
print("Observaciones meteorológicas cargadas:", len(clima_bruto))

clima = clima_bruto.copy()
clima["fecha_utc"] = pd.to_datetime(clima["DATE"], utc=True, errors="coerce")
clima["fecha_ny"] = clima["fecha_utc"].dt.tz_convert(ZONA_HORARIA)
inicio_local = INICIO_MES.tz_localize(ZONA_HORARIA)
fin_local = FIN_ANALISIS.tz_localize(ZONA_HORARIA)
clima = clima.loc[clima["fecha_ny"].between(inicio_local, fin_local, inclusive="left")].copy()

VARIABLES_CLIMA = ["temperature", "relative_humidity", "wind_speed", "precipitation", "visibility"]
clima[VARIABLES_CLIMA] = clima[VARIABLES_CLIMA].apply(pd.to_numeric, errors="coerce")
clima["hora"] = clima["fecha_ny"].dt.floor("h")
clima_horario = (
    clima.groupby("hora", as_index=False)
    .agg(
        temperatura_c=("temperature", "mean"),
        humedad_relativa=("relative_humidity", "mean"),
        viento=("wind_speed", "mean"),
        precipitacion_mm=("precipitation", lambda s: s.sum(min_count=1)),
        visibilidad=("visibility", "mean"),
        observaciones=("fecha_ny", "size"),
    )
)
if clima_horario["hora"].duplicated().any():
    raise ValueError("El resumen climático no es único por hora")
display(clima_horario.head())

"""### Ejercicio 2: cobertura temporal

Compara las horas esperadas de la ventana con las horas observadas en `clima_horario`. ¿Hay huecos?
"""

# Tu respuesta:
# horas_esperadas = ...
# horas_sin_clima = ...

"""<details><summary>Ver solución</summary>

```python
horas_esperadas = pd.date_range(inicio_local, fin_local, freq="h", inclusive="left")
horas_sin_clima = horas_esperadas.difference(clima_horario["hora"])
print("Horas esperadas:", len(horas_esperadas))
print("Horas sin observación:", len(horas_sin_clima))
display(horas_sin_clima[:10])
```
</details>

## 8. Unión zona-hora con clima

Cada fila zona-hora debe encontrar como máximo una fila climática. La unión izquierda conserva los pickups aunque el clima falte.
"""

zona_hora_clima = pickups_zona_hora.merge(
    clima_horario, left_on="pickup_hora", right_on="hora",
    how="left", validate="many_to_one", indicator=True,
)
assert len(zona_hora_clima) == len(pickups_zona_hora), "La unión alteró la cardinalidad izquierda"
auditoria_union = zona_hora_clima["_merge"].value_counts(dropna=False).rename_axis("resultado").to_frame("filas")
display(auditoria_union)
zona_hora_clima = zona_hora_clima.drop(columns="_merge")

"""### ¿Por qué el clima queda repetido por zona?

La unidad de `zona_hora_clima` es **una zona en una hora**. En cambio, `clima_horario` contiene una sola observación por hora. Cuando esa observación se une con varias zonas de la misma hora, pandas la copia en cada fila zona-hora.

Ejemplo conceptual:

| zona | hora | pickups | temperatura |
|---|---|---:|---:|
| A | 08:00 | 20 | 5 °C |
| B | 08:00 | 35 | 5 °C |
| C | 08:00 | 15 | 5 °C |

Los tres valores de `5 °C` no son mediciones diferentes: son la misma observación meteorológica replicada por la unión `many_to_one`. Esta repetición es intencional, no un duplicado accidental. Además, NOAA representa una estación meteorológica; no estamos estimando un clima diferente para cada zona.

## 9. Análisis exploratorio con pandas y matplotlib

Lee cada gráfico como evidencia descriptiva. Pregunta siempre: ¿qué unidad representa?, ¿qué filtros se aplicaron?, ¿qué explicación alternativa existe?
"""

viajes_por_hora = viajes_zonas.set_index("pickup_hora").resample("h").size()
ax = viajes_por_hora.plot(figsize=(12, 4), color="#1f77b4", linewidth=1.5)
ax.set(title="Viajes por hora", xlabel="Hora local", ylabel="Viajes")
plt.show()

top_zonas = viajes_zonas["pickup_zone"].value_counts().head(12).sort_values()
ax = top_zonas.plot.barh(figsize=(9, 5), color="#d95f02")
ax.set(title="Zonas con más pickups", xlabel="Viajes", ylabel="Zona de pickup")
plt.show()
display(top_zonas.sort_values(ascending=False).rename("pickups").to_frame())

patron = viajes_zonas.assign(
    dia=viajes_zonas["pickup_hora"].dt.day_name(),
    hora_dia=viajes_zonas["pickup_hora"].dt.hour,
).pivot_table(index="dia", columns="hora_dia", values="PULocationID", aggfunc="size", fill_value=0)
orden_dias = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
patron = patron.reindex([d for d in orden_dias if d in patron.index])
fig, ax = plt.subplots(figsize=(12, 4))
imagen = ax.imshow(patron, aspect="auto", cmap="YlOrRd")
ax.set(title="Mapa de calor de pickups por día y hora", xlabel="Hora", ylabel="Día")
ax.set_xticks(range(24), labels=range(24))
ax.set_yticks(range(len(patron.index)), labels=patron.index)
fig.colorbar(imagen, ax=ax, label="Pickups")
plt.show()

limite_99 = viajes_validos["duracion_min"].quantile(0.99)
ax = viajes_validos.loc[viajes_validos["duracion_min"] <= limite_99, "duracion_min"].plot.hist(
    bins=50, figsize=(9, 4), color="#7570b3", edgecolor="white"
)
ax.set(title="Distribución de duración (hasta percentil 99)", xlabel="Minutos", ylabel="Viajes")
plt.show()
print("Percentil 99 mostrado:", round(limite_99, 1), "minutos")

"""### 9.1. De zona-hora a una observación por hora

Para comparar la actividad total de taxis con el clima debemos volver de la unidad **zona-hora** a la unidad **hora**. En el ejemplo anterior:

```text
pickups = 20 + 35 + 15 = 70
temperatura = 5 °C
```

Por eso usamos operaciones diferentes:

- `sum` para `pickups`, porque cada zona aporta viajes distintos;
- `first` para temperatura y precipitación, porque cada fila contiene una copia del mismo clima horario.

Sumar la temperatura produciría `5 + 5 + 5 = 15 °C`, un valor sin interpretación física. El uso de `first` requiere comprobar antes que una misma hora no contenga valores climáticos diferentes entre zonas.
"""

# Verificamos el supuesto necesario para conservar una sola copia con 'first'.
variables_clima_repetidas = ["temperatura_c", "precipitacion_mm"]
consistencia_clima = (
    zona_hora_clima
    .groupby("pickup_hora")[variables_clima_repetidas]
    .nunique(dropna=False)
)
assert consistencia_clima.le(1).all().all(), (
    "Una misma hora contiene valores climáticos diferentes entre zonas"
)
print("Consistencia climática por hora: OK")

# El clima está repetido por zona; volvemos a una observación por hora.
comparacion_horaria = (
    zona_hora_clima.groupby("pickup_hora", as_index=False)
    .agg(
        pickups=("pickups", "sum"),
        temperatura_c=("temperatura_c", "first"),
        precipitacion_mm=("precipitacion_mm", "first"),
    )
)
assert not comparacion_horaria["pickup_hora"].duplicated().any()
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].scatter(comparacion_horaria["temperatura_c"], comparacion_horaria["pickups"], alpha=0.65, color="#1b9e77")
axes[0].set(xlabel="Temperatura (°C)", ylabel="Pickups por hora", title="Pickups y temperatura")
axes[1].scatter(comparacion_horaria["precipitacion_mm"], comparacion_horaria["pickups"], alpha=0.65, color="#377eb8")
axes[1].set(xlabel="Precipitación horaria (mm)", ylabel="Pickups por hora", title="Pickups y precipitación")
plt.tight_layout()
plt.show()
display(comparacion_horaria[["pickups", "temperatura_c", "precipitacion_mm"]].corr().round(3))

"""### Pregunta breve

¿Qué ocurriría si sumáramos la temperatura después de haberla replicado por zona?

<details><summary>Ver respuesta orientativa</summary>La misma observación se contabilizaría varias veces y produciría una temperatura sin interpretación física. Los pickups sí se suman porque cada zona aporta viajes diferentes; el clima se conserva una sola vez porque es el mismo valor replicado.</details>

### Ejercicio 3: interpretar sin exagerar

Escribe dos observaciones de los gráficos y una explicación alternativa. Evita frases causales como “la lluvia provoca...”.

**Tu respuesta:**

1. ...
2. ...
3. Explicación alternativa: ...

<details><summary>Ver pauta de solución</summary>Una respuesta sólida identifica dirección, magnitud o franjas horarias, menciona la ventana analizada y reconoce factores de confusión como hora pico, día de semana, aeropuerto, feriados o disponibilidad de taxis. Una correlación horaria no permite atribuir causalidad al clima.</details>

## 10. Exportar el producto fuera del repositorio

Antes de exportar comprobamos la clave, ordenamos el producto y usamos el directorio temporal del sistema. El nombre distingue el modo de clase del mes completo para no declarar una cobertura que no fue procesada.
"""

producto = zona_hora_clima.sort_values(["pickup_hora", "PULocationID"]).copy()
if producto.duplicated(["pickup_hora", "PULocationID"]).any():
    raise ValueError("La clave zona-hora no es única")

alcance = "primera_semana_enero_2024" if MODO_CLASE else "enero_2024"
ruta_producto = Path(tempfile.gettempdir()) / f"zona_hora_{alcance}.parquet"
producto.to_parquet(ruta_producto, index=False)
print("Producto temporal:", ruta_producto)
print("Unidad: zona de origen-hora local | Zona horaria:", ZONA_HORARIA)

"""## 11. Extensión espacial opcional

Esta celda descarga el ZIP del shapefile a un directorio temporal, extrae juntos sus componentes (`.shp`, `.dbf`, `.shx`, `.prj`) y construye un mapa Folium. La extracción explícita evita depender de que el backend geoespacial admita rutas virtuales `zip://`; al finalizar, el directorio temporal se elimina y no deja geometrías en el repositorio. Si `geopandas`, `folium` o `requests` no están instalados, informa exactamente cómo habilitar la sección y el resto del taller sigue siendo utilizable.
"""

try:
    import folium
    import geopandas as gpd
    import requests
    import zipfile
except ModuleNotFoundError as error:
    print(
        f"Sección espacial omitida: falta '{error.name}'. "
        "Descomenta `%pip install -q geopandas folium requests`, reinicia si es necesario y vuelve a ejecutar."
    )
else:
    with tempfile.TemporaryDirectory() as directorio_base:
        ruta_zip = Path(directorio_base) / "taxi_zones.zip"
        respuesta = requests.get(URL_GEOMETRIAS, timeout=60)
        respuesta.raise_for_status()
        ruta_zip.write_bytes(respuesta.content)
        if not zipfile.is_zipfile(ruta_zip):
            raise zipfile.BadZipFile("La descarga de zonas TLC no es un archivo ZIP válido")

        directorio_extraido = Path(directorio_base) / "taxi_zones_extraido"
        directorio_extraido.mkdir()
        with zipfile.ZipFile(ruta_zip) as archivo_zip:
            archivo_zip.extractall(directorio_extraido)

        archivos_shp = sorted(directorio_extraido.rglob("*.shp"))
        if not archivos_shp:
            raise FileNotFoundError("No se encontró un archivo .shp dentro del ZIP de zonas TLC")
        ruta_shp = next((ruta for ruta in archivos_shp if ruta.name == "taxi_zones.shp"), archivos_shp[0])
        geo_zonas = gpd.read_file(ruta_shp).to_crs(epsg=4326)

    pickups_mapa = viajes_zonas["PULocationID"].value_counts().rename("pickups").reset_index()
    geo_zonas["LocationID"] = pd.to_numeric(geo_zonas["LocationID"])
    geo_mapa = geo_zonas.merge(pickups_mapa, left_on="LocationID", right_on="PULocationID", how="left", validate="one_to_one")
    geo_mapa["pickups"] = geo_mapa["pickups"].fillna(0)
    min_x, min_y, max_x, max_y = geo_mapa.total_bounds
    centro = [(min_y + max_y) / 2, (min_x + max_x) / 2]
    mapa = folium.Map(location=centro, zoom_start=10, tiles="CartoDB positron")
    folium.Choropleth(
        geo_data=geo_mapa, data=geo_mapa, columns=["LocationID", "pickups"],
        key_on="feature.properties.LocationID", fill_color="YlOrRd",
        fill_opacity=0.7, line_opacity=0.3, legend_name="Pickups",
    ).add_to(mapa)
    folium.GeoJson(
        geo_mapa, style_function=lambda _: {"fillOpacity": 0, "weight": 0},
        tooltip=folium.GeoJsonTooltip(fields=["zone", "borough", "pickups"], aliases=["Zona", "Borough", "Pickups"]),
    ).add_to(mapa)
    display(mapa)

"""## 12. Conclusiones y límites

**Qué construimos**

- un proceso reproducible para enero de 2024, escalable de una semana al mes;
- una auditoría que hace visibles los criterios de exclusión;
- una tabla zona-hora enriquecida con clima mediante cardinalidad comprobada;
- visualizaciones temporales, espaciales y de asociación exploratoria.

**Límites que deben acompañar cualquier conclusión**

- Los registros son **viajes reportados de Yellow Taxi**, no demanda total, viajes no atendidos ni toda la movilidad de Nueva York.
- Una sola estación, `USW00094728`, no representa toda la variación meteorológica espacial de la ciudad.
- La cobertura y frecuencia de GHCNh pueden variar; resumir precipitación subhoraria exige revisar la documentación de medición.
- Las reglas de calidad y sus umbrales afectan los resultados y deben justificarse.
- La asociación entre pickups y clima está confundida por hora, día, localización, oferta, eventos y otros factores. **Correlación no implica causalidad.**
- `MODO_CLASE=True` describe solo la primera semana; para conclusiones mensuales se debe ejecutar el mes completo y evaluar estabilidad.

**Cierre:** ¿qué dato adicional pedirías para distinguir mejor demanda, oferta y viajes efectivamente realizados?




----------------------------------------------------------------------------------------------------------------------------------------------------------------------









# ***`Trabajo práctico: exploración de dos variables`***

***MILAGROS IDIARTE 37174***

Par elegido: PC-01 — pickups (columna 1) y temperatura_c (columna 2)

Vista analítica correspondiente: H (horaria) — una fila por hora, con pickups sumados por hora y temperatura_c tomada como first (después de verificar consistencia).

| Campo | Respuesta del estudiante |
|---|---|
| **Código y par elegido** | PC-01 — `pickups` (columna 1) y `temperatura_c` (columna 2) |
| **Pregunta exploratoria** | ¿Cómo varían los pickups de Yellow Taxi por hora junto con la temperatura del aire registrada, durante enero de 2024 en Nueva York? |
| **Significado de la primera columna** | `pickups`: cantidad de recogidas (pickups) de Yellow Taxi registradas durante una hora local dada, sumadas sobre todas las zonas de origen activas en esa hora. |
| **Significado de la segunda columna** | `temperatura_c`: temperatura del aire en grados Celsius, medida por la estación meteorológica NOAA de referencia, una observación resumida por hora. |
| **Tipo semántico de cada columna** | `pickups`: numérica discreta (conteo, no puede ser negativa). `temperatura_c`: numérica continua. |
| **Unidad analítica y vista** | Vista H (horaria) — una fila por hora local. `pickups` se obtiene sumando sobre zonas activas; `temperatura_c` se obtiene con `first` tras verificar que no hay más de un valor distinto por hora. |
| **Periodo y zona horaria** | `[2024-01-01, 2024-02-01)`, zona horaria `America/New_York` (enero de 2024 no tiene cambio de horario de verano, así que cada día tiene 24 horas). |
| **Población registrada** | Horas de enero de 2024 en las que hubo al menos un pickup registrado en alguna zona; el dato climático puede estar presente o faltante (NaN) según la cobertura de la estación NOAA. |
| **Denominador o tamaño válido** | 744 horas de enero de 2024 (todas con al menos un pickup registrado). De esas, 743 horas tienen temperatura válida y 1 hora tiene temperatura_c faltante (NaN, no se imputa como cero). |
| **Afirmaciones que los datos no permiten** | No se puede afirmar que la temperatura *cause* variaciones en los pickups (no hay diseño causal). Los pickups no representan la demanda total de viajes, solo los viajes de Yellow Taxi efectivamente realizados y reportados. Las horas son observaciones dependientes entre sí (autocorrelación temporal), no independientes. Un solo mes no permite generalizar a otros periodos del año. |
"""

# Verificación: temperatura_c no debe tener más de un valor distinto por hora
consistencia_temp = producto.groupby("pickup_hora")["temperatura_c"].nunique(dropna=False)
assert consistencia_temp.le(1).all(), (
    "Se encontró más de un valor de temperatura_c dentro de la misma hora"
)
print("Consistencia de temperatura_c por hora: OK")

por_hora = producto.groupby("pickup_hora", as_index=False).agg(
    pickups=("pickups", "sum"),
    temperatura_c=("temperatura_c", "first"),
)

print("Filas en por_hora (horas):", len(por_hora))
print("Horas con temperatura_c faltante:", por_hora["temperatura_c"].isna().sum())
display(por_hora.head())

# La clave de por_hora debe ser única
assert por_hora["pickup_hora"].is_unique, "pickup_hora no es única en por_hora"

# Cobertura temporal esperada vs observada
horas_esperadas = pd.date_range(
    INICIO_MES.tz_localize(ZONA_HORARIA), FIN_MES.tz_localize(ZONA_HORARIA),
    freq="h", inclusive="left",
)
horas_con_pickups = pd.DatetimeIndex(por_hora["pickup_hora"])
horas_sin_pickups = horas_esperadas.difference(horas_con_pickups)

print("Horas esperadas en enero:", len(horas_esperadas))
print("Horas con al menos un pickup:", len(horas_con_pickups))
print("Horas sin ningún pickup (ausentes de por_hora):", len(horas_sin_pickups))

# 1-4. Comprensión y cobertura de 'pickups'
print("Tipo de dato físico:", por_hora["pickups"].dtype)
print("Filas totales:", len(por_hora))
print("Valores válidos:", por_hora["pickups"].notna().sum())
print("Valores faltantes:", por_hora["pickups"].isna().sum())
print("Proporción de ceros:", (por_hora["pickups"] == 0).mean())
print("Mínimo:", por_hora["pickups"].min(), "| Máximo:", por_hora["pickups"].max())

# 7. Distribución
resumen_pickups = por_hora["pickups"].describe()
q1, q3 = por_hora["pickups"].quantile([0.25, 0.75])
iqr = q3 - q1
print(resumen_pickups)
print("IQR:", iqr)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
por_hora["pickups"].plot.hist(bins=30, ax=axes[0], color="#1f77b4", edgecolor="white")
axes[0].set(title="Distribución de pickups por hora (enero 2024)", xlabel="Pickups", ylabel="Frecuencia")

por_hora["pickups"].plot.box(ax=axes[1], vert=True)
axes[1].set(title="Boxplot de pickups por hora")
plt.tight_layout()
plt.show()

"""### Comprensión y cobertura — `pickups`

`pickups` es una variable agregada: se obtiene sumando la cantidad de
recogidas de Yellow Taxi de todas las zonas activas dentro de cada hora local.
No tiene valores faltantes ni ceros en las 744 horas de enero — cada hora del
mes tuvo al menos un pickup registrado. El mínimo (152) y el máximo (9027) son
valores plausibles para un servicio de taxis urbano; no hay violación de
dominio (no hay valores negativos).

### Distribución — `pickups`

La media (3933) es menor que la mediana (4519), lo que sugiere una
distribución con cola hacia valores bajos — compatible con las horas de
madrugada, que concentran mucha menos actividad que el resto del día. El IQR
(4127) es amplio en relación al rango total, reflejando la fuerte variación
entre horas pico y horas valle propia de un servicio de transporte urbano.
"""

# 1-4. Comprensión y cobertura de 'temperatura_c'
print("Tipo de dato físico:", por_hora["temperatura_c"].dtype)
print("Filas totales:", len(por_hora))
print("Valores válidos:", por_hora["temperatura_c"].notna().sum())
print("Valores faltantes:", por_hora["temperatura_c"].isna().sum())
print("Mínimo:", por_hora["temperatura_c"].min(), "| Máximo:", por_hora["temperatura_c"].max())

# ¿Cuál es la hora con temperatura faltante?
display(por_hora.loc[por_hora["temperatura_c"].isna()])

# 7. Distribución
resumen_temp = por_hora["temperatura_c"].describe()
q1t, q3t = por_hora["temperatura_c"].quantile([0.25, 0.75])
iqr_t = q3t - q1t
print(resumen_temp)
print("IQR:", iqr_t)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
por_hora["temperatura_c"].plot.hist(bins=25, ax=axes[0], color="#d95f02", edgecolor="white")
axes[0].set(title="Distribución de temperatura por hora (enero 2024)", xlabel="Temperatura (°C)", ylabel="Frecuencia")

por_hora["temperatura_c"].plot.box(ax=axes[1], vert=True)
axes[1].set(title="Boxplot de temperatura por hora")
plt.tight_layout()
plt.show()

# Contexto alrededor de la hora faltante
idx = por_hora.index[por_hora["pickup_hora"] == "2024-01-10 11:00:00-05:00"][0]
display(por_hora.loc[idx-3:idx+3])

"""### Comprensión y cobertura — `temperatura_c`

`temperatura_c` proviene de la estación meteorológica NOAA de referencia y fue
resumida a una observación por hora mediante `first`, después de comprobar que
no había más de un valor distinto de temperatura por hora entre las zonas
activas (repetición esperada por diseño, no un error).

**Faltantes:** hay 1 hora sin dato de temperatura, correspondiente al
2024-01-10 11:00. Las horas vecinas (9.4 °C a las 10:00, 10.0 °C a las 12:00)
muestran valores normales y coherentes entre sí, lo que es consistente con un
hueco puntual de reporte de la estación NOAA y no con un problema sistemático
del pipeline. El dato se conserva como faltante (NaN) y no se imputa. Los
pickups de esa misma hora (4843) están dentro del rango típico, sin relación
aparente con el faltante climático.

**Dominio:** el rango observado (-8.3 °C a 15.2 °C) es coherente con enero en
Nueva York; no se detecta violación de dominio.

### Distribución — `temperatura_c`

Media (2.74 °C) y mediana (2.8 °C) son prácticamente iguales, lo que sugiere
una distribución bastante simétrica, a diferencia de `pickups`. El histograma
se construyó con 25 bins (~1 °C por barra), suficiente para distinguir
variaciones diarias sin generar ruido excesivo dado el tamaño de la muestra
(n=743). El histograma muestra varios picos en vez de una campana suave; esto
podría reflejar los ciclos térmicos día/noche típicos de enero, aunque también
podría ser ruido propio de una muestra de tamaño moderado — no se puede
distinguir entre ambas explicaciones solo con esta vista.
"""

def detectar_anomalos_tukey(serie):
    q1, q3 = serie.quantile([0.25, 0.75])
    iqr = q3 - q1
    limite_inf = q1 - 1.5 * iqr
    limite_sup = q3 + 1.5 * iqr
    return limite_inf, limite_sup

# Pickups
li_pk, ls_pk = detectar_anomalos_tukey(por_hora["pickups"])
print(f"Límites Tukey para pickups: [{li_pk:.1f}, {ls_pk:.1f}]")
anomalos_pickups = por_hora.loc[
    (por_hora["pickups"] < li_pk) | (por_hora["pickups"] > ls_pk)
].sort_values("pickups")
print(f"Casos señalados en pickups: {len(anomalos_pickups)}")
display(anomalos_pickups)

# Temperatura
li_t, ls_t = detectar_anomalos_tukey(por_hora["temperatura_c"])
print(f"Límites Tukey para temperatura_c: [{li_t:.1f}, {ls_t:.1f}]")
anomalos_temp = por_hora.loc[
    (por_hora["temperatura_c"] < li_t) | (por_hora["temperatura_c"] > ls_t)
].sort_values("temperatura_c")
print(f"Casos señalados en temperatura_c: {len(anomalos_temp)}")
display(anomalos_temp)

"""### Casos potencialmente anómalos — regla de Tukey

Se aplicó la regla de Tukey (candidato si el valor cae fuera de
`[Q1 - 1.5·IQR, Q3 + 1.5·IQR]`) a ambas columnas de la vista horaria (n=744
para pickups, n=743 para temperatura_c, excluyendo el faltante).

| Variable | Límite inferior | Límite superior | Casos señalados |
|---|---|---|---|
| `pickups` | -4598.2 | 11909.8 | 0 |
| `temperatura_c` | -10.6 | 16.1 | 0 |

No se identificaron casos potencialmente anómalos por esta regla en ninguna de
las dos variables: todos los valores observados caen dentro del rango
esperado según la dispersión intercuartílica de enero de 2024. Esto no
significa que no existan horas inusuales (por ejemplo, la hora de mínimo
pickups o de temperatura mínima), sino que ninguna se aleja lo suficiente del
resto de la distribución como para ser marcada por este criterio estadístico
particular. No se excluye ni corrige ningún dato en esta etapa.
"""

# 1. Scatter plot
fig, ax = plt.subplots(figsize=(8, 6))
ax.scatter(por_hora["temperatura_c"], por_hora["pickups"], alpha=0.5, color="#1f77b4")
ax.set(
    title="Pickups por hora vs. temperatura (enero 2024, n=743)",
    xlabel="Temperatura (°C)",
    ylabel="Pickups por hora",
)
plt.show()

# 3-4. Correlaciones (con las filas donde ambas columnas son válidas)
datos_validos = por_hora.dropna(subset=["pickups", "temperatura_c"])
print("n usado en la correlación:", len(datos_validos))

pearson = datos_validos["pickups"].corr(datos_validos["temperatura_c"], method="pearson")
spearman = datos_validos["pickups"].corr(datos_validos["temperatura_c"], method="spearman")
print(f"Pearson: {pearson:.3f}")
print(f"Spearman: {spearman:.3f}")

"""### Relación entre pickups y temperatura

El diagrama de dispersión muestra una asociación positiva pero débil entre
`temperatura_c` y `pickups` (Pearson = 0.158, Spearman = 0.184, n=743). La
cercanía entre ambos coeficientes sugiere que no hay una desviación fuerte de
la linealidad que Spearman esté "rescatando".

Lo más notable del gráfico es la enorme dispersión vertical de `pickups` en
cada nivel de temperatura: a -5 °C y a 10 °C se observan por igual horas con
menos de 500 pickups y horas con más de 7000. Esto sugiere que otros factores
—probablemente la hora del día y el día de la semana— explican una porción
mucho mayor de la variación de `pickups` que la temperatura. La temperatura y
la hora del día no son independientes entre sí (las madrugadas tienden a ser
más frías en enero), por lo que parte de esta asociación débil podría estar
mediada por el ciclo horario en vez de reflejar un efecto directo del clima.
"""

# Puntos potencialmente influyentes: los extremos combinados de ambas variables
extremos = por_hora.dropna(subset=["pickups", "temperatura_c"]).copy()
print("Top 5 por pickups más alto:")
display(extremos.nlargest(5, "pickups"))
print("Top 5 por pickups más bajo:")
display(extremos.nsmallest(5, "pickups"))

"""### Forma, curvatura y agrupamientos

No se observa una relación lineal clara ni una curva evidente entre
`pickups` y `temperatura_c`. Tampoco se distinguen agrupamientos en el
espacio bidimensional de las dos variables tal como están graficadas. Sin
embargo, al inspeccionar los casos extremos surge un patrón claro: los 5
valores más altos de `pickups` (8395–9027) ocurren todos entre las 17:00 y
las 18:00 (hora pico vespertina), con temperaturas muy dispares entre sí
(-5.0 °C a 13.3 °C). Los 5 valores más bajos de `pickups` (152–183) ocurren
todos a las 03:00 (madrugada), también con temperaturas variadas (-3.3 °C a
3.3 °C). Este agrupamiento por hora del día, y no por temperatura, es
evidencia directa de que la hora del día es un factor mucho más determinante
de `pickups` que la temperatura, y refuerza la hipótesis de confusión
planteada más arriba. El pickup máximo (9027) ocurre a -5.0 °C, una
temperatura fría, lo que va *en contra* de la tendencia positiva débil
observada — no es un punto que infle artificialmente la correlación, sino
uno que la debilita.

### Comparación con y sin casos señalados

La regla de Tukey (sección 7) no señaló casos potencialmente anómalos en
`pickups` ni en `temperatura_c`, por lo que no existe un subconjunto "sin
anómalos" distinto del conjunto completo. Los coeficientes de correlación
reportados (Pearson = 0.158, Spearman = 0.184) ya reflejan la totalidad de
las 743 horas con ambos valores válidos, sin necesidad de una comparación
adicional en este punto.
"""

por_hora_enriquecido = por_hora.dropna(subset=["pickups", "temperatura_c"]).copy()
por_hora_enriquecido["hora_dia"] = por_hora_enriquecido["pickup_hora"].dt.hour

# Correlación global (ya la tenemos, la repetimos como referencia)
print("Correlación global — Pearson:", por_hora_enriquecido["pickups"].corr(por_hora_enriquecido["temperatura_c"]))

# Correlación por cada hora del día (0 a 23)
correlacion_por_hora = (
    por_hora_enriquecido.groupby("hora_dia")
    .apply(lambda g: pd.Series({
        "n": len(g),
        "pearson": g["pickups"].corr(g["temperatura_c"], method="pearson"),
        "spearman": g["pickups"].corr(g["temperatura_c"], method="spearman"),
        "pickups_promedio": g["pickups"].mean(),
    }))
)
display(correlacion_por_hora)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

correlacion_por_hora["pearson"].plot(ax=axes[0], marker="o", color="#1f77b4", label="Pearson")
correlacion_por_hora["spearman"].plot(ax=axes[0], marker="o", color="#d95f02", label="Spearman")
axes[0].axhline(0, color="gray", linewidth=0.8)
axes[0].set(title="Correlación pickups-temperatura por hora del día", xlabel="Hora del día", ylabel="Coeficiente")
axes[0].legend()

correlacion_por_hora["pickups_promedio"].plot(ax=axes[1], marker="o", color="#7570b3")
axes[1].set(title="Pickups promedio por hora del día", xlabel="Hora del día", ylabel="Pickups promedio")

plt.tight_layout()
plt.show()

def franja(h):
    if 0 <= h < 6:
        return "madrugada (0-5)"
    elif 6 <= h < 12:
        return "mañana (6-11)"
    elif 12 <= h < 18:
        return "tarde (12-17)"
    else:
        return "noche (18-23)"

por_hora_enriquecido["franja"] = por_hora_enriquecido["hora_dia"].apply(franja)

correlacion_por_franja = (
    por_hora_enriquecido.groupby("franja")
    .apply(lambda g: pd.Series({
        "n": len(g),
        "pearson": g["pickups"].corr(g["temperatura_c"], method="pearson"),
        "spearman": g["pickups"].corr(g["temperatura_c"], method="spearman"),
    }))
)
display(correlacion_por_franja)

"""### Análisis de sensibilidad: estratificación por hora del día

Se estratificó la muestra por hora del día para comprobar si la correlación
global (Pearson=0.158, Spearman=0.184, n=743) se sostiene dentro de
subgrupos más homogéneos en cuanto a actividad horaria. Esta estratificación
se definió antes de observar los resultados por franja.

**Por hora individual (n=31 por hora):** los coeficientes fluctúan entre
-0.14 y 0.21, cambiando de signo varias veces a lo largo del día. Dado el
tamaño de muestra reducido por hora, estas estimaciones individuales son
ruidosas y no deben sobre-interpretarse.

**Por franja horaria (n≈186, más estable):**

| Franja | Pearson | Spearman |
|---|---|---|
| Madrugada (0-5h) | 0.086 | 0.094 |
| Mañana (6-11h) | 0.099 | 0.119 |
| Tarde (12-17h) | -0.051 | 0.0003 |
| Noche (18-23h) | 0.135 | 0.159 |

En las cuatro franjas la correlación es más débil que la global, y en la
franja de la tarde prácticamente desaparece (Spearman ≈ 0). Esto es
compatible con un efecto de confusión tipo Simpson: la hora del día está
asociada tanto con el nivel de `pickups` (bajo en madrugada, alto en
tarde/noche, según el gráfico de pickups promedio por hora) como,
posiblemente, con la temperatura típica de ese momento del día. Al analizar
las 743 horas mezcladas sin distinguir la hora del día, la correlación
global aparece más fuerte que la que se observa dentro de cualquier franja
homogénea por separado, lo que sugiere que buena parte de la asociación
global no refleja un efecto directo de la temperatura sobre los pickups, sino
la superposición de dos ciclos horarios distintos.

## 10. Hallazgos finales

### Hallazgo 1 — Pickups por hora

**Alcance:** las 744 horas locales de enero de 2024 en Nueva York, agregando
pickups de Yellow Taxi de todas las zonas activas por hora.

**Observación:** `pickups` varía fuertemente a lo largo del día, entre un
mínimo de 152 (2024-01-30, 03:00) y un máximo de 9027 (2024-01-17, 18:00).
La media (3933) es menor que la mediana (4519), y el perfil horario muestra
un valle claro de madrugada (mínimo alrededor de las 4-5h) y un pico hacia
las 17-18h.

**Cobertura:** 744/744 horas con dato válido; no hay faltantes ni ceros en
esta columna.

**Interpretación:** la actividad de Yellow Taxi en enero de 2024 sigue un
ciclo diario marcado, con muy poca actividad de madrugada y un pico claro al
final de la tarde, consistente con patrones típicos de movilidad urbana
(horario laboral, salida del trabajo).

**Explicación alternativa:** la variación observada podría reflejar en parte
la disponibilidad de vehículos (menos taxis en circulación de madrugada) y
no solo la demanda de pasajeros; los datos de TLC no permiten distinguir
entre ambos factores.

**Límite:** `pickups` cuenta viajes efectivamente realizados y reportados
por Yellow Taxi, no la demanda total de traslados ni los pedidos no
atendidos.

**Siguiente comprobación posible:** desagregar por día de la semana
(laborable vs. fin de semana) para ver si el pico y el valle se mantienen
estables, o si difieren entre días.

---

### Hallazgo 2 — Temperatura por hora

**Alcance:** las horas de enero de 2024 con observación climática válida de
la estación NOAA de referencia (743 de 744 horas).

**Observación:** `temperatura_c` varió entre -8.3°C y 15.2°C, con media
(2.74°C) y mediana (2.8°C) muy cercanas entre sí, lo que sugiere una
distribución razonablemente simétrica. El histograma muestra varios picos en
vez de una campana suave.

**Cobertura:** 743 de 744 horas con dato válido (99.9%); la única hora
faltante (2024-01-10, 11:00) está rodeada de observaciones normales y
coherentes, consistente con un hueco puntual de reporte y no con un
problema sistemático.

**Interpretación:** enero de 2024 tuvo temperaturas típicas de invierno en
Nueva York, sin evidencia de valores fuera de rango o de un problema de
calidad relevante en la fuente climática.

**Explicación alternativa:** los múltiples picos del histograma podrían
reflejar ciclos térmicos día/noche reales, o simplemente ser ruido propio de
una muestra de tamaño moderado (n=743); no se puede distinguir entre ambas
opciones con esta sola vista.

**Límite:** la temperatura proviene de una única estación meteorológica y se
aplica por igual a toda la ciudad en cada hora; no captura variación espacial
entre zonas ni microclimas locales.

**Siguiente comprobación posible:** comparar la distribución de enero contra
otros meses de invierno de años anteriores para evaluar si 2024 fue un enero
típico o atípico.

---

### Hallazgo 3 — Relación entre pickups y temperatura

**Alcance:** las 743 horas de enero de 2024 con ambos valores válidos
simultáneamente.

**Observación:** la correlación global entre `pickups` y `temperatura_c` es
positiva pero débil (Pearson=0.158, Spearman=0.184). Al estratificar por
franja horaria, la correlación se debilita aún más dentro de cada franja
(entre -0.05 y 0.16 según Pearson) y en particular se anula en la franja de
la tarde (Spearman≈0), siendo en todos los casos menor que la correlación
global.

**Cobertura:** n=743 (todas las horas con ambos valores válidos); la única
hora excluida es la que carece de temperatura.

**Interpretación:** la asociación global entre temperatura y pickups es débil
y buena parte de ella parece explicarse por un factor compartido —la hora del
día— más que por un efecto directo del clima sobre la actividad de taxis: la
correlación es sistemáticamente más alta en el conjunto completo que dentro
de cualquier franja horaria homogénea, un patrón compatible con el efecto
Simpson.

**Explicación alternativa:** además de la hora del día, el día de la semana,
feriados o eventos puntuales podrían estar generando parte de la asociación
observada sin que medie ningún efecto directo de la temperatura.

**Límite:** este análisis es puramente descriptivo y no permite establecer
causalidad; tampoco corrige por dependencia temporal entre horas
consecutivas (autocorrelación), que no fue modelada explícitamente.

**Siguiente comprobación posible:** repetir el análisis controlando
simultáneamente por hora del día y día de la semana (por ejemplo, con un
modelo de regresión múltiple), para aislar mejor el efecto asociado
específicamente a la temperatura.

## 11. Límites y próximos pasos

### Límites generales del análisis

- Los datos de Yellow Taxi (TLC) representan viajes efectivamente realizados
  y reportados, no la demanda total de traslados ni los pedidos que no
  fueron atendidos.
- La temperatura proviene de una única estación NOAA y se aplica por igual a
  toda la ciudad en cada hora; no captura variación espacial ni microclimas.
- Las horas son observaciones dependientes entre sí (autocorrelación
  temporal): lo que ocurre en una hora está relacionado con la hora
  siguiente, por lo que el número de horas no equivale a esa misma cantidad
  de observaciones independientes.
- El periodo analizado es un único mes (enero de 2024); no se puede
  generalizar a otras épocas del año sin evidencia adicional.
- No se cuenta con un diseño experimental, por lo que ninguna de las
  asociaciones descriptas puede interpretarse como relación causal.
- La estratificación por hora del día (sección 9) sugiere un posible efecto
  Simpson o factor de confusión, pero no se controló simultáneamente por
  día de la semana ni por otros factores de calendario (feriados, eventos).

### Próximos pasos posibles

- Repetir el análisis controlando por hora del día y día de la semana en
  conjunto (por ejemplo, con un modelo de regresión múltiple), para separar
  mejor el efecto asociado a la temperatura del asociado al calendario.
- Extender el periodo a varios meses para evaluar si el patrón observado en
  enero de 2024 se sostiene en el tiempo.
- Explorar si feriados o eventos puntuales de enero (por ejemplo, algún fin
  de semana largo) explican parte de los valores extremos de `pickups`
  observados en los picos de las 17-18h.
"""